#!/usr/bin/python

pos=8
for i in range(1, pos+1):
    for j in range(pos-1, 0, -1)
        print " ",
    for j in range(0, i):
        print (chr(65+i)),
    for j in range(i-1, 0, -1):
        print (chr(64+i)),
    print
