#!/usr/bin/python
a=[1,3,5,7]
i=0
print a
print i
for i in range(0,4): #i=0～3
       if i==0:
               a[i]=a[i]*2
       elif i==1:
               a[i]=a[i]%2
       elif i==2:
               a[i]=a[i]*3
       else:
               a[i]=a[i]/3
print a
